name: Connected Check

on:
  push:
    branches:
      - '*'

  pull_request:
    branches:
      - master

jobs:
  run-connected-checks:
    # put [skip ci] into the commit message if you don't want to run this workflow

    runs-on: macos-latest

    timeout-minutes: 15

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: oracle
          java-version: 11

      - name: Set up build properties
        run: |
          echo 'licenceKey=""' > local.properties
          echo 'android.useAndroidX=true' >> gradle.properties
          echo 'android.enableJetifier=true' >> gradle.properties

      - name: Run connectedCheck
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          target: google_apis
          arch: x86_64
          script: ./gradlew connectedCheck